name = "travel-agent-scraper"
main = "src/index.ts"
compatibility_date = "2025-10-11"
usage_model = "bundled"

[observability]
enabled = true

[[browser]]
binding = "BROWSER"

[[queues.consumers]]
queue = "scraping-tasks"
max_batch_size = 5
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "scraping-dlq"

[[queues.consumers]]
queue = "scraping-priority"
max_batch_size = 2
max_batch_timeout = 10
max_retries = 5

d1_databases = [
  { binding = "DB", database_name = "travel-agent-db", database_id = "69777f92-2c68-4634-bb8f-ac7fe15704ea", migrations_dir = "../travel-agent-worker/migrations" }
]

[[r2_buckets]]
binding = "SCRAPED_DATA"
bucket_name = "travel-agent-scraped-data"

[[r2_buckets]]
binding = "CACHE_BUCKET"
bucket_name = "travel-agent-cache"

[[kv_namespaces]]
binding = "CACHE"
id = "fc75338297b74cd089fb79cb9a25fd07"
