/**
 * Extended environment types for the travel agent worker
 * The base Env interface is generated by wrangler types
 */

export interface WorkerEnv extends Env {
        CACHE: KVNamespace;
        SESSIONS: KVNamespace;
        SCRAPED_DATA: R2Bucket;
        USER_UPLOADS: R2Bucket;
        CACHE_BUCKET: R2Bucket;
        SCRAPING_QUEUE: Queue;
        PRIORITY_SCRAPING_QUEUE: Queue;
        TRAVEL_AGENT: DurableObjectNamespace;
        SCRAPING_AGENT: DurableObjectNamespace;
        CONVERSATION_MANAGER: DurableObjectNamespace;
        SESSION_MANAGER: DurableObjectNamespace;
}

/**
 * Vectorize document structure
 */
export interface VectorizeDocument {
        id: string;
        values: number[];
        metadata?: {
                type: 'hotel' | 'attraction' | 'review' | 'content';
                title?: string;
                description?: string;
                location?: string;
                tags?: string[];
                [key: string]: unknown;
        };
}
