/**
 * Extended environment types for the travel agent worker
 * The base Env interface is generated by wrangler types
 */

/**
 * Queue message structure for scraping tasks
 */
export interface ScrapingMessage {
	url: string;
	type: 'hotel' | 'attraction' | 'flight' | 'general';
	userId?: string;
	sessionId?: string;
	metadata?: Record<string, unknown>;
}

/**
 * Vectorize document structure
 */
export interface VectorizeDocument {
	id: string;
	values: number[];
	metadata?: {
		type: 'hotel' | 'attraction' | 'review' | 'content';
		title?: string;
		description?: string;
		location?: string;
		tags?: string[];
		[key: string]: unknown;
	};
}
